version: "3.8"
services:
  db:
    image: postgres:16-alpine
    container_name: parcial-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
  api:
    build: .
    container_name: parcial-api
    ports:
      - "${PORT}:3000"
    environment:
      PORT: ${PORT}
      STUDENT_NAME: ${STUDENT_NAME}
      STUDENT_EXPEDIENTE: ${STUDENT_EXPEDIENTE}
      STUDENT_CODIGO: ${STUDENT_CODIGO}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net
volumes:
  db_data:
networks:
  app_net:
    driver: bridge
